### ISSUE TITLE
prints for shop limited editions

### ISSUE THREAD

**Issue by ftloa-altonwebsites** [altonwebsites/altonwebsites_ftloa#28]
the shop limited editions page was originally intended only for prints and not originals.  I can see that you have populated this page with the originals from the Featured section eg Rose Hilton, John Harvey etc. and I can see the logic in this as they all link up. We actually think this is quite sensible as it means people can browse all our stock in one place and if they see an image rather than knowing a name, it will attract them.  It means I will need to change the button to SHOP and change the text which I can send though to you. It would be really helpful though if there could be some sort of sort functionality option (price lowest - highest ) and even better if you could select originals or select prints.  You need to just tell us Steve when we have overstretched your time as I don't want to keep moving the goalposts, it's just that sometimes ideas get triggered off! Equally I have more limited editions and biogs that I could send you but again don't know what your expectations are here, so just let me know. I will wait to hear from you before I revised the text as that will dictate the content in terms of the search functionality.

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
Sorry I didn't get to this one sooner. I didn't appreciate that it was only for prints. Do you want me to change the navigation menu and the home page box from Shop Limited Editions to Shop, or something similar?
If you tell me what you want the visitor to sort by, I'll figure out how to make it work. Some ideas...
Sort by price (low to high), 
Sort by Price (high to low), 
Show only originals,
Show only prints,
Show all,
Show only those in stock

I'm happy to keep going with any features that you think of, although I should finish in a couple of weeks so I can get the business started on the island. The site was a lot trickier than others I've done because of the different ways we're showing the same info across different pages. I'm quite enjoying the challenge to be honest. How about I add the sorting/filters to the shop page and then we publish the site to loveourart.co.uk as fixed-width, i.e. the mbile visitor will see the same as appears on the desktop. I can work on the mobile/tablet layouts while you're entering the biogs & any other artwork. Nobody will find the site until I either submit it to the search engines, or we post links somewhere on the web. Almost a soft launch. You can be populating the content while I'm working on the layout. Does that make sense?

**Comment by ftloa-altonwebsites** [comment]
hi steve

yes please change to SHOP and I will send over some new copy.

I am happy with your suggested sort options, the default should be showing all in stock, I would rather not show items that are sold in the ‘shop’ but dont’ worry if this is a problem. It isn’t a big deal.  Will it be easy for me to categorise them when I add new ones?

Also happy to do the going live bit as you suggest as I will need to play around with it to make sure I can add things properly and upload photos!  It has been a couple of years since I have managed a website!

also wanted to say that if you wanted to promote the fact that you designed the site somewhere along the footer we are very happy for you to do that.

many tanks

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎8‎ ‎June‎ ‎2015 ‎19‎:‎55
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, 
Sorry I didn't get to this one sooner. I didn't appreciate that it was only for prints. Do you want me to change the navigation menu and the home page box from Shop Limited Editions to Shop, or something similar?
If you tell me what you want the visitor to sort by, I'll figure out how to make it work. Some ideas...
Sort by price (low to high), 
Sort by Price (high to low), 
Show only originals,
Show only prints,
Show all,
Show only those in stock

I'm happy to keep going with any features that you think of, although I should finish in a couple of weeks so I can get the business started on the island. The site was a lot trickier than others I've done because of the different ways we're showing the same info across different pages. I'm quite enjoying the challenge to be honest. How about I add the sorting/filters to the shop page and then we publish the site to loveourart.co.uk as fixed-width, i.e. the mbile visitor will see the same as appears on the desktop. I can work on the mobile/tablet layouts while you're entering the biogs & any other artwork. Nobody will find the site until I either submit it to the search engines, or we post links somewhere on the web. Almost a soft launch. You can be populating the content while I'm working on the layout. Does that make sense?

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
I've added the sorting for the shop, made the changes to the text on the Shop page. You may need to refresh your browser a couple of times to see the changes (inc the change I made to the search box to add the magnifying glass). I've still to enable the filtering of original vs prints. This took a while because I had to change the way Artists and Artwork are related to each other. Will add the original/print filters tomorrow.

**Comment by altonwebsites** [comment]
I am happy with your suggested sort options, the default should be showing all in stock, I would rather not show items that are sold in the ‘shop’ but dont’ worry if this is a problem.
- Shop no longer shows Sold items - that was an easy one

Will it be easy for me to categorise them when I add new ones? 
- Yes, it's all pretty simple once you've done it a couple of times!

Also happy to do the going live bit as you suggest as I will need to play around with it to make sure I can add things properly and upload photos! 
- Great, will finish the shop filtering then get the live site set up

also wanted to say that if you wanted to promote the fact that you designed the site somewhere along the footer we are very happy for you to do that.
Thank you! I'll make sure it's discrete : )

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
I've added the filters for Originals and Prints to the shop. I need to line up some of the text on the "filter bar". There are 2 versions of the shop to look at. 

[http:www.altonwebsites.com/ftloa12](http:www.altonwebsites.com/ftloa12)
[http:www.altonwebsites.com/ftloa13](http:www.altonwebsites.com/ftloa13)

The second version has the shop text down by the footer so the user doesn't have to scroll past it each time to get to the images. If you prefer this version, it may need a slight rewrite.

Let me know which you prefer.

**Comment by ftloa-altonwebsites** [comment]
hi steve

I think we need to show the explanatory text at the top but can I make a suggestion?  

I think we could lose the large image to the right of the text (currently Sandra Blow) and just have the text going across so it takes much less space and you can see the sort functions straight away then when you click on that shop button.

I also think, now looking at it, we should have a sort by ARTIST instead of by title (based on surname), hopefully that is easy to change?

great functionality, love it.

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Thursday‎, ‎11‎ ‎June‎ ‎2015 ‎18‎:‎59
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, 
I've added the filters for Originals and Prints to the shop. I need to line up some of the text on the "filter bar". There are 2 versions of the shop to look at. 

http:www.altonwebsites.com/ftloa12
http:www.altonwebsites.com/ftloa13

The second version has the shop text down by the footer so the user doesn't have to scroll past it each time to get to the images. If you prefer this version, it may need a slight rewrite.

Let me know which you prefer.
