### ISSUE TITLE
Search results changes

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#29]
Hi Lyndsay, 
When the artist's name is put into the search box the results now show only the link to the artist where previously it also showed all the work by the artist. e.g. typing Bethel shows the one link to  David Bethel's profile where all his work is displayed. 

This is due to the way I had to rearrange the Artist/Artwork relationship in the database to get the shop sorting working. Apart from the sorting, the big advantage of this is when you add new artwork to the site, it's no longer necessary to then go to the artist's page to link the new artwork - it's all now done on the one page. Are you OK with this? It also makes the search results more concise when you're trying to find a single artist's biog and artwork.

All the other search results behave as they did previously, inc text searches e.g. "Ives", and if the artist's name appears in another artist's biog, it will appear as you'd expect. 

Let me know what you think about this
Thanks, Steve

**Comment by ftloa-altonwebsites** [comment]
yes this is good steve

thanks

Sent from Windows Mail

From: Alton Websites
Sent: ‎Wednesday‎, ‎10‎ ‎June‎ ‎2015 ‎18‎:‎56
To: altonwebsites/altonwebsites_ftloa

Hi Lyndsay, 
When the artist's name is put into the search box the results now show only the link to the artist where previously it also showed all the work by the artist. e.g. typing Bethel shows the one link to David Bethel's profile where all his work is displayed. 

This is due to the way I had to rearrange the Artist/Artwork relationship in the database to get the shop sorting working. Apart from the sorting, the big advantage of this is when you add new artwork to the site, it's no longer necessary to then go to the artist's page to link the new artwork - it's all now done on the one page. Are you OK with this? It also makes the search results more concise when you're trying to find a single artist's biog and artwork.

All the other search results behave as they did previously, inc text searches e.g. "Ives", and if the artist's name appears in another artist's biog, it will appear as you'd expect. 

Let me know what you think about this
Thanks, Steve

**Comment by altonwebsites** [comment]
Close issue
