### ISSUE TITLE
exporting data

### ISSUE THREAD

**Issue by ftloa-altonwebsites** [altonwebsites/altonwebsites_ftloa#34]
just exported the subscribers data for the first time - is there a way of avoiding getting lots of additional stuff that we don't need? it exported multiple columns with commas and colons in which I would then have to manually delete. not sure if I did it right!
also if we export regularly will it only pick up new subscribers each time?
thanks!

**Comment by altonwebsites** [comment]
This is a .CSV (comma separated values) file. Do you use Excel? 
On the Export page you can choose to separate the values with commas, semicolons or tabs. You're only collecting email addresses so the output is a bit overcomplicated. 

If you're keeping an Excel file for these, open the file and select File -> Import and select the CSV file created from the export. Choose Delimited (rather than fixed width) and click Next. Then select commas/semicolons/tabs (whichever you choose during the Export. It'll show an example below of how the info will look when imported. Then select Finish and choose which cell on the spreadsheet to start the import to. Then delete the unnecessary cells. There's currently no way to export only a single field. 

"also if we export regularly will it only pick up new subscribers each time?"
Good question. No, it'll export all of them. Recommend importing to a new spreadsheet and looking at the date field for subscribers since your last export, then copying these to your working spreadsheet sheet. 

I've tried to use the more professional plugins (WooCommerce and Newsletter) so that your site has what it needs behind the scenes to expand with your business. At this stage they seem to be overkill if you see what I mean. Hopefully it'll be better in the long term.

**Comment by altonwebsites** [comment]
All newsletter subscribers are captured via the newsletter sign-up bar and the contact form and sent Mailchimp's website. Please can you test this to confirm that you see email addresses added to your FTLOA List on MailChimp.
