### ISSUE TITLE
Newsletter sign-up - privacy statement, welcome email, defaults

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#38]
Hi Lyndsday, 
Where do you want the privacy statement to appear? Mailchimp has an option of sending a welcome email out when a visitor signs up. It could go in that, or beneath the contact form, or in the FAQs, or beneath the newsletter sign-up bar (though not sure how that would look)

Also, do you want the tickbox on the contact form to be ticked by default?

**Comment by ftloa-altonwebsites** [comment]
hi steve

if we could have the privacy statement on the welcome email that would be great.  I was happy with the wording on the other welcome email (with the one typo change) if it could be added to that?

May also be a good idea to have it in very small font beneath the tick box so they know before ticking it on the contact page.  Best to leave the  box unticked I think otherwise they are not ‘opting in’?

ps - just got back from meeting up with Sigrun and was telling her all about the website and what a great job you have done!

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Thursday‎, ‎2‎ ‎July‎ ‎2015 ‎14‎:‎44
To: altonwebsites/altonwebsites_ftloa

Hi Lyndsday, 
Where do you want the privacy statement to appear? Mailchimp has an option of sending a welcome email out when a visitor signs up. It could go in that, or beneath the contact form, or in the FAQs, or beneath the newsletter sign-up bar (though not sure how that would look)

Also, do you want the tickbox on the contact form to be ticked by default?

**Comment by altonwebsites** [comment]
Created a welcome email on MailChimp via Lists -> FTLOA -> Sign up Forms -> General Forms Select -> Final "Welcome Email"
Also added text beneath the contact form that you can edit in the Contact Us editing page

**Comment by ftloa-altonwebsites** [comment]
I tried to make the amend with the word on the welcome email myself but I got as far as General Forms / Select above and then couldn't see anything about Final Welcome Email? It seems to want me to create a new form.

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
It's in the dropdown box under "Create Forms". 

<img width="674" alt="screen shot 2015-07-15 at 10 41 33" src="https://cloud.githubusercontent.com/assets/10417228/8695638/24cc4886-2ade-11e5-88ba-e50beb5604a8.png">

Then hover over the original wording and there should be an edit button in the top right

<img width="731" alt="screen shot 2015-07-15 at 10 42 04" src="https://cloud.githubusercontent.com/assets/10417228/8695637/24c99c9e-2ade-11e5-8931-82a0b09feb82.png">

**Comment by ftloa-altonwebsites** [comment]
great got it thanks!

Sent from Windows Mail

From: Alton Websites
Sent: ‎Wednesday‎, ‎15‎ ‎July‎ ‎2015 ‎10‎:‎43
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, 
It's in the dropdown box under "Create Forms".

 screen shot 2015-07-15 at 10 41 33 
 screen shot 2015-07-15 at 10 42 04
