### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#7]
Investigate what’s searchable in the database,
Will need a search results page with results ordered into appropriate 'categories'

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
Can you take a look at the new search box and results please please - suggest typing "Ives" to get a range of results. 
Can I have feedback on the curent location of the search box - There's not a lot of space in the header - an icon rather than "search" might work better. Also, the search results are grouped in by artwork, artists, and pages. Is this as you expected?
Thanks, Steve

**Comment by ftloa-altonwebsites** [comment]
hi steve

I like the functionality of the search. I typed in a name as well as ‘drawing’ and ‘linocut’ so that all looks good.  but I think it isn’t obvious that it’s a search box.

Is there a possibility of squeezing it in on the far right next to Contact?

I like the way that the TATE do their searches http://www.tate.org.uk/art/artworks/greaves-title-not-known-p04244 so within the box it says for example Find art or artists and then the magnifying glass.

Is that poss?

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Friday‎, ‎5‎ ‎June‎ ‎2015 ‎18‎:‎41
To: altonwebsites/altonwebsites_ftloa

Hi Lyndsay, 
Can you take a look at the new search box and results please please - suggest typing "Ives" to get a range of results. 
Can I have feedback on the curent location of the search box - There's not a lot of space in the header - an icon rather than "search" might work better. Also, the search results are grouped in by artwork, artists, and pages. Is this as you expected?
Thanks, Steve

**Comment by ftloa-altonwebsites** [comment]
hi steve, also just to add on the search results where it displays images, it is only showing the title and price, would be helpful if it showed the artists name.

many thanks

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Friday‎, ‎5‎ ‎June‎ ‎2015 ‎18‎:‎41
To: altonwebsites/altonwebsites_ftloa

Hi Lyndsay, 
Can you take a look at the new search box and results please please - suggest typing "Ives" to get a range of results. 
Can I have feedback on the curent location of the search box - There's not a lot of space in the header - an icon rather than "search" might work better. Also, the search results are grouped in by artwork, artists, and pages. Is this as you expected?
Thanks, Steve

**Comment by altonwebsites** [comment]
Hi Lyndsay, added the search box to the navigation bar. Also, added details to the search results for artwork - e.g. artist's name and price.

**Comment by ftloa-altonwebsites** [comment]
great this looks good

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎8‎ ‎June‎ ‎2015 ‎19‎:‎01
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, added the search box to the navigation bar. Also, added details to the search results for artwork - e.g. artist's name and price.
